const Admin=require('../models/adminModel');
const {hashPassword,verifyPassword,createSessionToken,hashToken}=require('../utils/password');
const {validateLogin,validateProfile,validatePasswordChange}=require('../validators/authValidator');
async function login(req,res,next){try{const v=validateLogin(req.body);if(!v.valid)return res.status(400).json({success:false,message:v.errors[0],errors:v.errors});const {email,password,remember}=v.value;const admin=await Admin.findByEmail(email);if(!admin||!verifyPassword(password,admin.password_salt,admin.password_hash))return res.status(401).json({success:false,message:'Invalid email or password.'});await Admin.deleteExpiredSessions();const token=createSessionToken();const tokenHash=hashToken(token);const expiresAt=new Date(Date.now()+(remember?7*24:8)*60*60*1000);await Admin.createSession(admin.id,tokenHash,expiresAt);res.json({success:true,message:'Login successful.',token,expires_at:expiresAt.toISOString(),data:Admin.publicAdmin(admin)});}catch(error){next(error);}}
async function logout(req,res,next){try{await Admin.deleteSession(req.authTokenHash);res.json({success:true,message:'Logged out successfully.'});}catch(error){next(error);}}
async function me(req,res){res.json({success:true,data:Admin.publicAdmin(req.admin)});}
async function updateProfile(req,res,next){try{const v=validateProfile(req.body);if(!v.valid)return res.status(400).json({success:false,message:v.errors[0],errors:v.errors});if(await Admin.findEmailConflict(v.value.email,req.admin.id))return res.status(409).json({success:false,message:'That email address is already in use.'});await Admin.updateProfile(req.admin.id,v.value);res.json({success:true,message:'Profile updated successfully.',data:Admin.publicAdmin(await Admin.findById(req.admin.id))});}catch(error){next(error);}}
async function changePassword(req,res,next){try{const v=validatePasswordChange(req.body);if(!v.valid)return res.status(400).json({success:false,message:v.errors[0],errors:v.errors});const admin=await Admin.findById(req.admin.id);if(!admin||!verifyPassword(v.value.currentPassword,admin.password_salt,admin.password_hash))return res.status(400).json({success:false,message:'Current password is incorrect.'});const {salt,hash}=hashPassword(v.value.newPassword);await Admin.updatePassword(admin.id,salt,hash);await Admin.deleteAllSessions(admin.id);res.json({success:true,message:'Password changed successfully. Please login again.'});}catch(error){next(error);}}
module.exports={login,logout,me,updateProfile,changePassword};
