const Student = require('../models/studentModel');
const { validateStudent, parseListQuery } = require('../validators/studentValidator');
const parseId = (value) => { const id = Number.parseInt(value, 10); return Number.isInteger(id) && id > 0 ? id : null; };
async function getStudents(req,res,next){ try { const filters=parseListQuery(req.query); const {rows,total}=await Student.getAllStudents(filters); res.json({success:true,data:rows,pagination:{page:filters.page,limit:filters.limit,total,pages:Math.max(1,Math.ceil(total/filters.limit))}}); } catch(error){ next(error); } }
async function getSummary(req,res,next){ try { res.json({success:true,data:await Student.getSummary()}); } catch(error){ next(error); } }
async function getStudentById(req,res,next){ try { const id=parseId(req.params.id); if(!id) return res.status(400).json({success:false,message:'Invalid student ID.'}); const student=await Student.getStudentById(id); if(!student) return res.status(404).json({success:false,message:'Student not found.'}); res.json({success:true,data:student}); } catch(error){ next(error); } }
async function addStudent(req,res,next){ try { const validation=validateStudent(req.body); if(!validation.valid) return res.status(400).json({success:false,message:validation.errors[0],errors:validation.errors}); const s=validation.value; const conflict=await Student.findConflict(s.student_id,s.email); if(conflict){ const field=conflict.student_id===s.student_id?'Student ID':'Email'; return res.status(409).json({success:false,message:`${field} already exists.`}); } const result=await Student.addStudent(s); res.status(201).json({success:true,message:'Student added successfully.',data:await Student.getStudentById(result.insertId)}); } catch(error){ next(error); } }
async function updateStudent(req,res,next){ try { const id=parseId(req.params.id); if(!id) return res.status(400).json({success:false,message:'Invalid student ID.'}); if(!await Student.getStudentById(id)) return res.status(404).json({success:false,message:'Student not found.'}); const validation=validateStudent(req.body); if(!validation.valid) return res.status(400).json({success:false,message:validation.errors[0],errors:validation.errors}); const s=validation.value; const conflict=await Student.findConflict(s.student_id,s.email,id); if(conflict){ const field=conflict.student_id===s.student_id?'Student ID':'Email'; return res.status(409).json({success:false,message:`${field} already exists.`}); } await Student.updateStudent(id,s); res.json({success:true,message:'Student updated successfully.',data:await Student.getStudentById(id)}); } catch(error){ next(error); } }
async function deleteStudent(req,res,next){ try { const id=parseId(req.params.id); if(!id) return res.status(400).json({success:false,message:'Invalid student ID.'}); const result=await Student.deleteStudent(id); if(!result.affectedRows) return res.status(404).json({success:false,message:'Student not found.'}); res.json({success:true,message:'Student deleted successfully.'}); } catch(error){ next(error); } }
module.exports={getStudents,getSummary,getStudentById,addStudent,updateStudent,deleteStudent};
