const express=require('express');
const authController=require('../controllers/authController');
const requireAuth=require('../middleware/auth');
const router=express.Router();
router.post('/login',authController.login);
router.post('/logout',requireAuth,authController.logout);
router.get('/me',requireAuth,authController.me);
router.put('/profile',requireAuth,authController.updateProfile);
router.put('/password',requireAuth,authController.changePassword);
module.exports=router;
