const express=require('express');
const studentController=require('../controllers/studentController');
const requireAuth=require('../middleware/auth');
const router=express.Router();
router.use(requireAuth);
router.get('/stats/summary',studentController.getSummary);
router.get('/',studentController.getStudents);
router.get('/:id',studentController.getStudentById);
router.post('/',studentController.addStudent);
router.put('/:id',studentController.updateStudent);
router.delete('/:id',studentController.deleteStudent);
module.exports=router;
