const db = require('../config/db');
function buildWhere({ search, department, year, status }) { const clauses = []; const values = []; if (search) { clauses.push('(student_id LIKE ? OR full_name LIKE ? OR email LIKE ?)'); const like = `%${search}%`; values.push(like, like, like); } if (department) { clauses.push('department = ?'); values.push(department); } if (year) { clauses.push('academic_year = ?'); values.push(year); } if (status) { clauses.push('status = ?'); values.push(status); } return { sql: clauses.length ? `WHERE ${clauses.join(' AND ')}` : '', values }; }
async function getAllStudents(filters) { const { sql, values } = buildWhere(filters); const offset = (filters.page - 1) * filters.limit; const [countRows] = await db.query(`SELECT COUNT(*) AS total FROM students ${sql}`, values); const [rows] = await db.query(`SELECT id, student_id, full_name, email, phone, gender, department, academic_year, dob, parent_name, parent_phone, address, status, created_at, updated_at FROM students ${sql} ORDER BY id DESC LIMIT ? OFFSET ?`, [...values, filters.limit, offset]); return { rows, total: Number(countRows[0]?.total || 0) }; }
async function getSummary() { const [rows] = await db.query("SELECT COUNT(*) AS total, SUM(status='Active') AS active, SUM(status='Inactive') AS inactive, COUNT(DISTINCT department) AS departments FROM students"); const r = rows[0] || {}; return { total: Number(r.total || 0), active: Number(r.active || 0), inactive: Number(r.inactive || 0), departments: Number(r.departments || 0) }; }
async function getStudentById(id) { const [rows] = await db.query('SELECT * FROM students WHERE id = ? LIMIT 1', [id]); return rows[0] || null; }
async function findConflict(studentId, email, excludeId = 0) { const [rows] = await db.query('SELECT id, student_id, email FROM students WHERE id <> ? AND (student_id = ? OR email = ?) LIMIT 1', [excludeId, studentId, email]); return rows[0] || null; }
async function addStudent(s) { const [result] = await db.query('INSERT INTO students (student_id, full_name, email, phone, gender, department, academic_year, dob, parent_name, parent_phone, address, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [s.student_id,s.full_name,s.email,s.phone,s.gender,s.department,s.academic_year,s.dob,s.parent_name,s.parent_phone,s.address,s.status]); return result; }
async function updateStudent(id,s) { const [result] = await db.query('UPDATE students SET student_id=?, full_name=?, email=?, phone=?, gender=?, department=?, academic_year=?, dob=?, parent_name=?, parent_phone=?, address=?, status=? WHERE id=?', [s.student_id,s.full_name,s.email,s.phone,s.gender,s.department,s.academic_year,s.dob,s.parent_name,s.parent_phone,s.address,s.status,id]); return result; }
async function deleteStudent(id) { const [result] = await db.query('DELETE FROM students WHERE id = ?', [id]); return result; }
module.exports = { getAllStudents, getSummary, getStudentById, findConflict, addStudent, updateStudent, deleteStudent };
