const state={page:1,limit:10,pages:1,search:'',department:'',year:''};
document.addEventListener('DOMContentLoaded',async()=>{try{const admin=await SMS.requireAuth();if(!admin)return;SMS.bindLogoutLinks();bindFilters();bindTableActions();bindPagination();await Promise.all([loadStudents(),loadSummary()]);}catch(error){console.error(error);window.alert(error.message);}});
function bindFilters(){const search=document.getElementById('studentSearch');const department=document.getElementById('departmentFilter');const year=document.getElementById('yearFilter');search?.addEventListener('input',SMS.debounce(()=>{state.search=search.value.trim();state.page=1;loadStudents();},300));department?.addEventListener('change',()=>{state.department=department.value;state.page=1;loadStudents();});year?.addEventListener('change',()=>{state.year=year.value;state.page=1;loadStudents();});}
function bindPagination(){document.getElementById('prevPage')?.addEventListener('click',()=>{if(state.page>1){state.page--;loadStudents();}});document.getElementById('nextPage')?.addEventListener('click',()=>{if(state.page<state.pages){state.page++;loadStudents();}});}
function bindTableActions(){document.getElementById('studentTableBody')?.addEventListener('click',async(event)=>{const button=event.target.closest('button[data-action]');if(!button)return;const id=button.dataset.id;if(button.dataset.action==='view')await viewStudent(id);if(button.dataset.action==='delete')await deleteStudent(id);});}
async function loadStudents(){const params=new URLSearchParams({page:String(state.page),limit:String(state.limit)});if(state.search)params.set('search',state.search);if(state.department)params.set('department',state.department);if(state.year)params.set('year',state.year);try{const result=await SMS.request(`/students?${params}`);const p=result.pagination||{};state.page=p.page||1;state.pages=p.pages||1;renderStudents(result.data||[]);updatePagination(p);}catch(error){renderStudents([]);window.alert(error.message);}}
async function loadSummary(){try{const r=await SMS.request('/students/stats/summary');const s=r.data||{};setText('summaryTotalStudents',s.total??0);setText('summaryActiveStudents',s.active??0);setText('summaryInactiveStudents',s.inactive??0);setText('summaryDepartments',s.departments??0);}catch(error){console.error(error);}}
function renderStudents(students){const body=document.getElementById('studentTableBody');if(!body)return;if(!students.length){body.innerHTML='<tr><td colspan="9">No students found.</td></tr>';return;}body.innerHTML=students.map((s)=>`<tr><td>${SMS.escapeHtml(s.student_id)}</td><td>${SMS.escapeHtml(s.full_name)}</td><td>${SMS.escapeHtml(s.gender)}</td><td>${SMS.escapeHtml(s.department)}</td><td>${SMS.escapeHtml(s.academic_year)}</td><td>${SMS.escapeHtml(s.email)}</td><td>${SMS.escapeHtml(s.phone)}</td><td>${SMS.escapeHtml(s.status)}</td><td><button class="view-btn" data-action="view" data-id="${s.id}">View</button> <a href="edit-student.html?id=${s.id}" class="edit-btn">Edit</a> <button class="delete-btn" data-action="delete" data-id="${s.id}">Delete</button></td></tr>`).join('');}
function updatePagination(p){setText('studentCountDisplay',`Total Students : ${p.total??0}`);setText('pageIndicator',`${p.page||1} / ${p.pages||1}`);const prev=document.getElementById('prevPage');const next=document.getElementById('nextPage');if(prev)prev.disabled=(p.page||1)<=1;if(next)next.disabled=(p.page||1)>=(p.pages||1);}
async function viewStudent(id){try{const {data:s}=await SMS.request(`/students/${id}`);window.alert(['Student Details','',`Student ID : ${s.student_id}`,`Name       : ${s.full_name}`,`Gender     : ${s.gender}`,`Department : ${s.department}`,`Year       : ${s.academic_year}`,`Email      : ${s.email}`,`Phone      : ${s.phone}`,`Status     : ${s.status}`].join('\n'));}catch(error){window.alert(error.message);}}
async function deleteStudent(id){if(!window.confirm('Are you sure you want to permanently delete this student?'))return;try{const r=await SMS.request(`/students/${id}`,{method:'DELETE'});window.alert(r.message);await Promise.all([loadStudents(),loadSummary()]);}catch(error){window.alert(error.message);}}
function setText(id,value){const el=document.getElementById(id);if(el)el.textContent=String(value);}
